dist: trusty
sudo: false
language: c
compiler: clang

branches:
  only:
    - master

env:
  global:
    - BOTAN_INSTALL="$HOME/builds/botan-install"
    - CMOCKA_INSTALL="$HOME/builds/cmocka-install"

cache:
  directories:
    - "$BOTAN_INSTALL"
    - "$CMOCKA_INSTALL"

install:
  - ./ci/install.sh

script:
  - ./ci/main.sh

after_success:
  - ./ci/success.sh
